### ISSUE TITLE
The MAUI community misses you`

### ISSUE THREAD

**Issue by tanakamawere** [naweed/mkbhd-clone#1]
Sorry for MAUI disappointing you in the way it did...

I learnt MAUI from your videos, and since you left for Flutter, haven't found anyone else with more in-depth, real world tutorials as yourself.

Hope all is well. (Please come back😂it's stable now😂)

**Comment by naweed** [comment]
Hi @tanakamawere 
Good to hear such good remarks from you.

I have moved on from Maui and am very happy and satisfied with Flutter. Even with 100% stability in Maui, I cannot create polished apps as easily as Flutter.

Hope you understand.

**Comment by tanakamawere** [comment]
Fair enough. 

Yesterday, I was trying to use Maps in MAUI and you can be assured that you'd find dozens of examples in Flutter but very few for Xamarin and MAUI, which made me jealous of the move you made.

Just to pick your mind a bit, sorry to bother.
Even in 100% stability with MAUI, what have been the biggest advantages of Flutter in your experience?

**Comment by naweed** [comment]
@tanakamawere 

I blogged about my (initial) journey a couple of years back. You can check it out: https://blogs.xgenoapps.com/post/2023/01/02/flutter-journey-confessions

If I have to sum it up:
1) It is extremely stable
2) Extremely easy
3) Huge community support (Facebook pages, LinkedIn group, Twitter communities, YouTube channels)
4) Thousands and thousands of components (you can only imagine such a thing in Xamarin/Maui)
5) High performant apps
6) Polished apps

As an example, this MKBHD clone app took me around 5-6 hours to build, and this involved researching on the MKBHD APIs. And imagine the UI that I have (staggered GridView). Try doing that in Maui.

I am not trying to deter you from Maui. One should use what they feel comfortable with. In the past 1.5 years, I have built 5-6 complex applications using Flutter.

**Comment by tanakamawere** [comment]
Alright. Thank you.

All te best.
